### ISSUE TITLE
Steam not found

### ISSUE THREAD

**Issue by somyk33** [magynhard/halflife_goldsrc_linux_font_patches#1]
I'm currently on Linux Mint 21.1 Cinnamon. What should I do?

![image](https://github.com/magynhard/halflife_goldsrc_linux_font_patches/assets/73316425/f4c1b12a-0a8a-4efa-b12d-e93c09ad2544)

**Comment by magynhard** [comment]
Thank you for your request.

Where is Steam installed on your system?

I might consider a environment parameter, so you can modify the default of `~/.local/share/Steam` where this script is looking for the Steam installation.

**Comment by somyk33** [comment]
~/.steam$
That's the Steam location

**Comment by somyk33** [comment]
Just now managed to edit a little your setup.sh and run it.
Thanks
