### ISSUE TITLE
Default trebuchet font

### ISSUE THREAD

**Issue by SkyLLerGithub** [magynhard/halflife_goldsrc_linux_font_patches#3]
Hello :)
Is this project still being maintained? I have some requests.
I would love to have the default trebuchet MS font like on windows, it seems that 25th anniversary Half-Life update has a complete overhaul for the fonts.
And does this still work on the 25th Anniversary edition of CS 1.6?
Thanks.

**Comment by magynhard** [comment]
@SkyLLerGithub thank you for your info. I did not notice the 25th anniversary update and did not play since then again.

Depending on the necessary changes i might provide some updates.

I have not tested my patch on the 25th anniversary version, even not played the 25h anniversary version at all.

So the 25th version is working fine without any font patch, but you just do not like the new font when running on linux?

**Comment by magynhard** [comment]
Did just a quick review. The patch does not work on the 25h version anymore.

Some font issues seems to be fixed, especially in the main menu.

But the default chat font is still not very readable on lightful maps like dust, but even better than before.

I will have another look again within the next weeks.

**Comment by magynhard** [comment]
The patch worked again, when i completely reinstalled the game (all Half-Life 1 and its mods, and deleting the directory "Half Life" inside "steamapps/common" and applied it again.

**Comment by SkyLLerGithub** [comment]
> The patch worked again, when i completely reinstalled the game (all Half-Life 1 and its mods, and deleting the directory "Half Life" inside "steamapps/common" and applied it again.

Does the game comes with its own fonts?
Checking /GAME/platform/resources i saw a folder about linux fonts.

**Comment by SkyLLerGithub** [comment]
> @SkyLLerGithub thank you for your info. I did not notice the 25th anniversary update and did not play since then again.
> 
> Depending on the necessary changes i might provide some updates.
> 
> I have not tested my patch on the 25th anniversary version, even not played the 25h anniversary version at all.
> 
> So the 25th version is working fine without any font patch, but you just do not like the new font when running on linux?

Yes that is correct, I never liked the anti aliasing fonts in the Linux port of the game and I favor the windows version fonts more. I haven't tried the patch yet but I liked the fonts that the patches uses for the chat. Also is the DHUD fonts changed aswell? In the pre 25th anniversary version of the game they are way too big.

DHUD
![image-12.png](https://github.com/magynhard/halflife_goldsrc_linux_font_patches/assets/161835713/8082e5e8-6104-469a-88e9-bf64958c6d67)



Thank you for your work btw, it was a pain to just get pre 25th anniversary update properly functioning and working. Works like yours makes the game a lot of enjoyable to play.

**Comment by magynhard** [comment]
Basically you can just fork my repo and replace the font assignments inside the scheme files with the trebuchet MS font and installing that font on your linux.

But as far, as i remember, i tried that also when i created the patch. But the linux version rendered the fonts different than the windows version, so they did not look good. Maybe that changed with the anniversary edition.

It was a coincidence, that i found a font that rendered very pretty like here. I tried a lot.


I do not know, if the game comes with own fonts, i guess it uses system fonts.
The DHUD might be have been changed to Noto Fonts. You can just try the patch, it creates backups of the scheme files and with the uninstall command you can restore them.

**Comment by SkyLLerGithub** [comment]
> Basically you can just fork my repo and replace the font assignments inside the scheme files with the trebuchet MS font and installing that font on your linux.
> 
> But as far, as i remember, i tried that also when i created the patch. But the linux version rendered the fonts different than the windows version, so they did not look good. Maybe that changed with the anniversary edition.
> 
> It was a coincidence, that i found a font that rendered very pretty like here. I tried a lot.
> 
> I do not know, if the game comes with own fonts, i guess it uses system fonts. The DHUD might be have been changed to Noto Fonts. You can just try the patch, it creates backups of the scheme files and with the uninstall command you can restore them.

Thank you, I'll mark this as closed then.
